import Head from 'next/head';
import classes from '/src/styles/Home.module.css';
import { Header } from '/src/components/Header';
import { Footer } from '/src/components/Footer';
import { Todo } from '/src/features/Todo';
import { Sidebar } from '/src/components/Sidebar';
// import { CreateNewPostBtn } from '/src/components/CreateNewPostBtn';

export default function Home() {
  return (
    <div className={classes.container}>
      <Head>
        <title>Top</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Header />
      <div className={classes.main}>
        {/* <CreateNewPostBtn /> */}
        <Sidebar />
        <Todo />
      </div>
      <Footer />
    </div>
  );
}
