import Head from 'next/head';
import classes from '/src/styles/Home.module.css';
import { Header } from '/src/components/Header';
import { Footer } from '/src/components/Footer';
import { Sidebar } from '/src/components/Sidebar';
import { Form } from '/src/components/Form';

export default function CreateNewPost() {
  return (
    <div className={classes.container}>
      <Head>
        <title>新規作成</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Header />
      <div className={classes.main}>
        <Sidebar />
        <Form />
      </div>
      <Footer />
    </div>
  );
}
