import Head from 'next/head';
import classes from '/src/styles/Home.module.css';
import { Header } from '/src/components/Header';
import { Footer } from '/src/components/Footer';
import { Sidebar } from '/src/components/Sidebar';
import Link from 'next/link';

export default function Home() {
  return (
    <div className={classes.container}>
      <Head>
        <title>Top</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Header />
      <div className={classes.main}>
        <Sidebar />
        <div className={classes.topContents}>
          <h1>Hello Guest !</h1>
          <h2>こちらはTopページです。</h2>
          <p>
            このアプリの概要について知りたい場合はヘッダーの「
            <Link className={classes.topLink} href='/about'>
              About
            </Link>
            」をクリックしてください。
          </p>
          <p>
            このアプリについて問い合わせたい場合はヘッダーの「
            <Link className={classes.topLink} href='/contact'>
              Contact
            </Link>
            」をクリックしてください。
          </p>
          <p>
            Todoリストを作りたい場合はサイドバーの「
            <Link
              className={classes.topLink}
              href='/top/sidebar/create_new_post'
            >
              新規作成
            </Link>
            」をクリックしてください。
          </p>
          <p>
            これまでに作ったTodoリストを見る・編集する場合はサイドバーの「
            <Link className={classes.topLink} href='/top/sidebar/latest'>
              新着順
            </Link>
            」をクリックしてください。
          </p>
        </div>
      </div>
      <Footer />
    </div>
  );
}
