import Head from 'next/head';
import classes from '/src/styles/Home.module.css';
import { Header } from '/src/components/Header';
import { Footer } from '/src/components/Footer';
import { Sidebar } from '/src/components/Sidebar';

export default function Home() {
  return (
    <div className={classes.container}>
      <Head>
        <title>Top</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Header />
      <div className={classes.main}>
        <Sidebar />
        <div className={classes.topContents}>
          <h1>Hello Guest !</h1>
          <h2>こちらはTopページです。</h2>
          <p>
            このアプリの概要について知りたい場合はヘッダーの「About」をクリックしてください。
          </p>
          <p>
            このアプリについて問い合わせたい場合はヘッダーの「Contact」をクリックしてください。
          </p>
          <p>
            Todoリストを作りたい場合はサイドバーの「新規作成」をクリックしてください。
          </p>
          <p>
            これまでに作ったTodoリストを見る・編集する場合はサイドバーの「新着順」をクリックしてください。
          </p>
        </div>
      </div>
      <Footer />
    </div>
  );
}
